name: Create Release PR

on:
  push:
    branches:
      - develop

jobs:
  call-create-release-pr-workflow:
    uses: atsutama2/auto-release-pr/.github/workflows/create-pr-workflow.yml@develop
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}