name: Trigger Release PR Workflow

on:
  workflow_call:
    secrets:
      accessToken:
        required: true

jobs:
  trigger:
    uses: atsutama2/auto-release-pr/.github/workflows/create-release-pr.yml@develop
    secrets:
      accessToken: ${{ secrets.ACCESS_TOKEN }}